docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: intro.md
    - Reference:
      - 'Routing': routing.md
      - 'Default Services': services.md
    - Migration:
      - 'Version 2 to Version 3': migration/v2-to-v3.md
site_name: zend-mvc-i18n
site_description: 'Integration between zend-mvc and zend-i18n'
repo_url: 'https://github.com/zendframework/zend-mvc-i18n'
